version: '3'
services:
  app: 
    build: .
    volumes:
      - .:/app
      - /app/vender/bundle
    ports:
      - 127.0.0.1:4567:4567
    environment:
        - MYSQL_HOST=db
        - MYSQL_USER=root
        - MYSQL_PASS=secret
        - MYSQL_DATABASE=nopochat_development
  db:
    image: mysql:5.7
    volumes:
      - .:/app
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
  nginx:
    build: ./nginx
    ports:
      - 127.0.0.1:3000:80
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/etc/nginx/html/foo
  netdata:
    image: titpetric/netdata
    volumes:
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
    ports:
      - 127.0.0.1:19999:19999
    restart: always


